package com.example.presentation.evacuation

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Dangerous
import androidx.compose.material.icons.filled.DirectionsWalk
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.NearMe
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.domain.model.EvacuationAction
import com.example.domain.model.ResourceStatus
import com.example.domain.model.RouteStatus
import com.example.presentation.components.EmergencyTopBar
import com.example.presentation.components.EvacuationActionCard
import com.example.presentation.components.SafetyDisclaimerCard
import com.example.presentation.viewmodel.JeevanSetuViewModel
import com.example.ui.theme.AppBackground
import com.example.ui.theme.BorderSubtle
import com.example.ui.theme.CautionAmber
import com.example.ui.theme.EmergencyRed
import com.example.ui.theme.MintDeep
import com.example.ui.theme.MintLight
import com.example.ui.theme.MintPrimary
import com.example.ui.theme.SafetyGreen
import com.example.ui.theme.SurfaceWhite
import com.example.ui.theme.TextPrimary
import com.example.ui.theme.TextSecondary

@Composable
fun EvacuationScreen(
    viewModel: JeevanSetuViewModel,
    onBack: () -> Unit,
    onNavigateToMap: () -> Unit,
    onNavigateToSafeLocations: () -> Unit
) {
    val dashboardState by viewModel.dashboardState.collectAsStateWithLifecycle()
    val waterEst by viewModel.waterEstimate.collectAsStateWithLifecycle()
    val foodEst by viewModel.foodEstimate.collectAsStateWithLifecycle()
    val fuelEst by viewModel.fuelEstimate.collectAsStateWithLifecycle()
    val isOnline by viewModel.isOnline.collectAsStateWithLifecycle()

    var selectedRouteStatus by remember { mutableStateOf(RouteStatus.UNKNOWN) }
    var hasActiveStructuralThreat by remember { mutableStateOf(false) }
    var isWaterRisingOrFireSpreading by remember { mutableStateOf(false) }
    var isAnalysisGenerated by remember { mutableStateOf(false) }

    // Evaluated Decision Action
    var currentDecision by remember { mutableStateOf(EvacuationAction.SHELTER_IN_PLACE) }
    var decisionHeadline by remember { mutableStateOf("") }
    var decisionDetail by remember { mutableStateOf("") }
    var reasonsList by remember { mutableStateOf(listOf<String>()) }

    fun computeEvacuationDecision() {
        val reasons = mutableListOf<String>()
        val decision: EvacuationAction
        val headline: String
        val detail: String

        // 1. Evaluate Staying Risk vs Fleeing Route Risk
        if (isWaterRisingOrFireSpreading || hasActiveStructuralThreat) {
            reasons.add("Immediate active danger at current shelter (structural breach, fire, or rising floodwater).")

            if (selectedRouteStatus == RouteStatus.FLOODED || selectedRouteStatus == RouteStatus.DANGEROUS) {
                // Route is dangerous! Do NOT blindly tell user to evacuate into raging torrents!
                decision = EvacuationAction.SHELTER_IN_PLACE
                headline = "HIGH STAY DANGER, BUT ROUTE IS COMPROMISED: SEEK VERTICAL REFUGE"
                detail = "Your current building is facing high danger, but outside routes are actively flooded or hazardous. Entering fast-moving floodwater or wildfire smoke on foot is extremely dangerous. Move to the highest stable floor, roof, or reinforced room. Do NOT enter submerged streets. Signal for official rescue teams."
                reasons.add("Route is impassable/flooded: Moving outdoors carries immediate casualty risk.")
            } else if (selectedRouteStatus == RouteStatus.PARTIALLY_BLOCKED || selectedRouteStatus == RouteStatus.APPEARS_SAFE) {
                decision = EvacuationAction.EVACUATE_IF_SAFE
                headline = "EVACUATION STRONGLY ADVISED VIA CONFIRMED PATH"
                detail = "Current location poses significant life danger, and an external evacuation path is reportedly open. Evacuate immediately toward the designated shelter. Take essential go-bag, drinking water, and identification."
                reasons.add("A viable evacuation corridor exists to reach higher ground/shelter.")
            } else {
                // Route unknown
                decision = EvacuationAction.PREPARE_TO_EVACUATE
                headline = "CRITICAL SITUATION: VERIFY SAFE ROUTE BEFORE MOVING"
                detail = "Danger is escalating at your shelter. Before stepping into the hazard zone, visually inspect local street exits. If roads are submerged under swift currents (> 6 inches), remain at high elevation. Move only if safe traversal is confirmed."
                reasons.add("External route status is unconfirmed.")
            }
        } else {
            // Low to moderate in-place risk
            if (waterEst.status == ResourceStatus.CRITICAL || foodEst.status == ResourceStatus.CRITICAL) {
                reasons.add("Survival supplies depleted: Water/food reserves are critical.")
                if (selectedRouteStatus == RouteStatus.APPEARS_SAFE) {
                    decision = EvacuationAction.EVACUATE_IF_SAFE
                    headline = "EVACUATE FOR RESOURCE DEPLETION VIA SAFE ROUTE"
                    detail = "While the structure remains intact, critical survival supplies have run out. Travel calmly to the nearest community relief shelter during daylight hours."
                } else {
                    decision = EvacuationAction.PREPARE_TO_EVACUATE
                    headline = "PREPARE TO EVACUATE: IDENTIFY SAFE CORRIDOR"
                    detail = "Resource shortages are imminent. Plan an evacuation journey, locate the nearest open distribution shelter, and check route accessibility."
                }
            } else {
                decision = EvacuationAction.SHELTER_IN_PLACE
                headline = "SHELTER IN PLACE IS CURRENTLY RECOMMENDED"
                detail = "Your current location does not exhibit immediate life-threatening structural danger based on current input. Moving outside during natural disasters exposes you to falling debris, flash currents, and traffic congestion. Remain sheltered, conserve water and phone battery, and monitor emergency channels."
                reasons.add("Structure is currently stable and dry.")
                reasons.add("Adequate survival resources currently available.")
            }
        }

        currentDecision = decision
        decisionHeadline = headline
        decisionDetail = detail
        reasonsList = reasons
        isAnalysisGenerated = true
    }

    Scaffold(
        containerColor = AppBackground,
        topBar = {
            EmergencyTopBar(
                title = "SHOULD I EVACUATE?",
                isOnline = isOnline,
                onBack = onBack
            )
        }
    ) { innerPadding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .background(AppBackground)
                .padding(innerPadding)
                .testTag("evacuation_screen"),
            contentPadding = PaddingValues(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                    border = androidx.compose.foundation.BorderStroke(1.dp, BorderSubtle)
                ) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                imageVector = Icons.Default.Shield,
                                contentDescription = null,
                                tint = MintPrimary,
                                modifier = Modifier.size(24.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "OFFLINE EVACUATION DECISION ENGINE",
                                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold, color = TextPrimary)
                            )
                        }
                        Text(
                            text = "This system balances the DANGER OF STAYING against the DANGER OF MOVING. It will never advise stepping blindly into dangerous floodwaters.",
                            style = MaterialTheme.typography.bodySmall.copy(color = TextSecondary)
                        )
                    }
                }
            }

            // Interactive Threat Checks
            item {
                Text(
                    text = "A. CURRENT LOCATION THREAT LEVEL",
                    style = MaterialTheme.typography.labelMedium.copy(
                        letterSpacing = 1.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextSecondary
                    )
                )
            }

            item {
                ThreatCheckCard(
                    title = "Is floodwater rising or fire spreading toward your shelter?",
                    subtitle = "Water entering rooms, rapid river rise, or smoke plume advancing",
                    checked = isWaterRisingOrFireSpreading,
                    onToggle = { isWaterRisingOrFireSpreading = !isWaterRisingOrFireSpreading }
                )
            }

            item {
                ThreatCheckCard(
                    title = "Is the building structurally compromised or tilting?",
                    subtitle = "Heavy cracks, partial collapse, mudflow pressure, or roof breach",
                    checked = hasActiveStructuralThreat,
                    onToggle = { hasActiveStructuralThreat = !hasActiveStructuralThreat }
                )
            }

            // Route Status Selection
            item {
                Text(
                    text = "B. EVACUATION ROUTE STATUS",
                    style = MaterialTheme.typography.labelMedium.copy(
                        letterSpacing = 1.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextSecondary
                    )
                )
            }

            RouteStatus.values().forEach { status ->
                item {
                    RouteOptionCard(
                        status = status,
                        isSelected = selectedRouteStatus == status,
                        onSelect = { selectedRouteStatus = status }
                    )
                }
            }

            // Nearest Safe Location Card
            item {
                Text(
                    text = "C. NEAREST SAVED DESTINATION",
                    style = MaterialTheme.typography.labelMedium.copy(
                        letterSpacing = 1.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextSecondary
                    )
                )
            }

            item {
                val nearest = dashboardState.nearestSafeLocation
                val dist = dashboardState.distanceToNearestKm
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { onNavigateToSafeLocations() },
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                    border = androidx.compose.foundation.BorderStroke(1.dp, BorderSubtle)
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Box(
                            modifier = Modifier
                                .size(40.dp)
                                .clip(CircleShape)
                                .background(MintLight),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(
                                imageVector = Icons.Default.NearMe,
                                contentDescription = null,
                                tint = MintDeep,
                                modifier = Modifier.size(22.dp)
                            )
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = nearest?.name ?: "No Safe Location Saved",
                                style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold, color = TextPrimary)
                            )
                            Text(
                                text = if (dist != null) "Approx. ${String.format("%.1f", dist)} km straight-line" else "Tap to add community shelters",
                                style = MaterialTheme.typography.labelSmall.copy(color = TextSecondary)
                            )
                        }
                    }
                }
            }

            item {
                Button(
                    onClick = { computeEvacuationDecision() },
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(54.dp)
                        .testTag("analyze_evacuation_button"),
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = MintPrimary)
                ) {
                    Text("EVALUATE EVACUATION DECISION", fontWeight = FontWeight.Bold, color = Color.White)
                }
            }

            // Output Results
            if (isAnalysisGenerated) {
                item {
                    EvacuationActionCard(action = currentDecision)
                }

                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(14.dp),
                        colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                        border = androidx.compose.foundation.BorderStroke(1.5.dp, BorderSubtle)
                    ) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Text(
                                text = decisionHeadline,
                                style = MaterialTheme.typography.titleMedium.copy(
                                    fontWeight = FontWeight.Bold,
                                    color = TextPrimary
                                )
                            )
                            Text(
                                text = decisionDetail,
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    lineHeight = 22.sp,
                                    color = TextPrimary
                                )
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = "DECISION REASONING:",
                                style = MaterialTheme.typography.labelSmall.copy(
                                    letterSpacing = 1.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = TextSecondary
                                )
                            )
                            reasonsList.forEach { reason ->
                                Row(verticalAlignment = Alignment.Top) {
                                    Text("• ", color = MintPrimary, fontWeight = FontWeight.Bold)
                                    Text(
                                        text = reason,
                                        style = MaterialTheme.typography.bodySmall.copy(color = TextPrimary)
                                    )
                                }
                            }
                        }
                    }
                }

                item {
                    Button(
                        onClick = onNavigateToMap,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp),
                        shape = RoundedCornerShape(10.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = MintDeep)
                    ) {
                        Icon(imageVector = Icons.Default.NearMe, contentDescription = null, tint = Color.White)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("VIEW ROUTE DIRECTION ON OFFLINE MAP", fontWeight = FontWeight.Bold, color = Color.White)
                    }
                }
            }

            item {
                SafetyDisclaimerCard()
            }
        }
    }
}

@Composable
fun ThreatCheckCard(
    title: String,
    subtitle: String,
    checked: Boolean,
    onToggle: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onToggle() },
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (checked) Color(0xFFFFF4F4) else SurfaceWhite
        ),
        border = androidx.compose.foundation.BorderStroke(
            1.dp,
            if (checked) EmergencyRed else BorderSubtle
        )
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = title,
                    style = MaterialTheme.typography.bodyMedium.copy(
                        fontWeight = FontWeight.Bold,
                        color = if (checked) EmergencyRed else TextPrimary
                    )
                )
                Text(
                    text = subtitle,
                    style = MaterialTheme.typography.labelSmall.copy(
                        color = TextSecondary
                    )
                )
            }
            Box(
                modifier = Modifier
                    .size(24.dp)
                    .clip(CircleShape)
                    .border(2.dp, if (checked) EmergencyRed else BorderSubtle, CircleShape)
                    .background(if (checked) EmergencyRed else Color.Transparent),
                contentAlignment = Alignment.Center
            ) {
                if (checked) {
                    Icon(
                        imageVector = Icons.Default.CheckCircle,
                        contentDescription = null,
                        tint = Color.White,
                        modifier = Modifier.size(16.dp)
                    )
                }
            }
        }
    }
}

@Composable
fun RouteOptionCard(
    status: RouteStatus,
    isSelected: Boolean,
    onSelect: () -> Unit
) {
    val color = when (status) {
        RouteStatus.APPEARS_SAFE -> SafetyGreen
        RouteStatus.PARTIALLY_BLOCKED -> CautionAmber
        RouteStatus.FLOODED -> EmergencyRed
        RouteStatus.DANGEROUS -> EmergencyRed
        RouteStatus.UNKNOWN -> BorderSubtle
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onSelect() },
        shape = RoundedCornerShape(10.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isSelected) color.copy(alpha = 0.12f) else SurfaceWhite
        ),
        border = androidx.compose.foundation.BorderStroke(
            if (isSelected) 1.5.dp else 1.dp,
            if (isSelected) color else BorderSubtle
        )
    ) {
        Row(
            modifier = Modifier.padding(14.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = status.label,
                style = MaterialTheme.typography.bodyMedium.copy(
                    fontWeight = FontWeight.SemiBold,
                    color = if (isSelected) (if (status == RouteStatus.UNKNOWN) TextPrimary else color) else TextPrimary
                ),
                modifier = Modifier.weight(1f)
            )
            if (isSelected) {
                Icon(
                    imageVector = Icons.Default.CheckCircle,
                    contentDescription = null,
                    tint = if (status == RouteStatus.UNKNOWN) MintPrimary else color,
                    modifier = Modifier.size(20.dp)
                )
            }
        }
    }
}
